// Server-side tool registry for the /api/chat consigliere.
// Each tool has an OpenAI-style JSON schema declaration + an executor
// that takes the current in-memory dashboard data and returns a plain object.
// The /api/chat endpoint runs the tool-use loop: LLM picks tool → we execute
// → feed the result back until the model produces a final assistant message.
//
// Map-control tools (toggle_layer, focus_map, set_time, compute_passes)
// are NOT registered here — they land in Phase 5 as CLIENT-side tool_calls
// executed in the browser against Cesium.

const CHOKEPOINTS = {
  hormuz: { label: 'Strait of Hormuz', lat: 26.5, lon: 56.5, note: '20% of world oil' },
  suez: { label: 'Suez Canal', lat: 30.5, lon: 32.3, note: '12% of world trade' },
  malacca: { label: 'Strait of Malacca', lat: 2.5, lon: 101.5, note: '25% of world trade' },
  'bab-el-mandeb': { label: 'Bab el-Mandeb', lat: 12.6, lon: 43.3, note: 'Red Sea gateway' },
  taiwan: { label: 'Taiwan Strait', lat: 24.0, lon: 119.0, note: '88% of largest container ships' },
  bosporus: { label: 'Bosphorus', lat: 41.1, lon: 29.1, note: 'Black Sea access' },
  panama: { label: 'Panama Canal', lat: 9.1, lon: -79.7, note: '5% of world trade' },
  'good-hope': { label: 'Cape of Good Hope', lat: -34.4, lon: 18.5, note: 'Suez alternative' },
};

// Haversine distance in km
function haversine(lat1, lon1, lat2, lon2) {
  const toRad = (d) => (d * Math.PI) / 180;
  const R = 6371;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a = Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

// Trim large payloads so the tool result fits a sensible token budget
function trimArray(arr, max = 20) {
  if (!Array.isArray(arr)) return arr;
  return arr.slice(0, max);
}

// ─── Tool schemas (OpenAI tools API format) ────────────────────────────────

export const TOOL_SCHEMAS = [
  {
    type: 'function',
    function: {
      name: 'get_briefing_summary',
      description: 'Top-level snapshot of the current intelligence picture: last sweep time, source health, market direction (risk-on / risk-off / mixed), delta change counts, and headline metrics (VIX, WTI, Brent, HY spread).',
      parameters: { type: 'object', properties: {}, required: [] },
    },
  },
  {
    type: 'function',
    function: {
      name: 'list_sources',
      description: 'List every OSINT source currently reporting data, its last-sweep status (ok / error), and a one-line description. Use this first if you need to know what data is available.',
      parameters: { type: 'object', properties: {}, required: [] },
    },
  },
  {
    type: 'function',
    function: {
      name: 'query_source',
      description: 'Fetch the current payload from a named source. Use list_sources first to see valid names. Returns a trimmed object safe to reason over. Examples: "yfinance" for market snapshot, "gdelt" for global news events, "firms" for thermal anomaly counts, "adsb" for military/commercial flight activity, "ships" for maritime chokepoint status, "space" for satellite + launch activity.',
      parameters: {
        type: 'object',
        properties: {
          source: {
            type: 'string',
            description: 'Source name (e.g. yfinance, fred, gdelt, firms, adsb, opensky, ships, space, acled, reliefweb, who, ofac, opensanctions, bluesky, reddit, telegram, kiwisdr, noaa, epa, patents, bls, treasury, eia, gscpi, usaspending, comtrade, safecast)',
          },
          limit: {
            type: 'integer',
            description: 'Max number of records to return for list-shaped fields (default 20)',
            default: 20,
          },
        },
        required: ['source'],
      },
    },
  },
  {
    type: 'function',
    function: {
      name: 'get_active_alerts',
      description: 'Recent delta-engine alerts: what changed since the previous sweep, with severity (critical / notable / routine) and direction. Returns the last N critical and notable signals.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer', default: 10 },
        },
        required: [],
      },
    },
  },
  {
    type: 'function',
    function: {
      name: 'get_trade_ideas',
      description: 'Current leverage-able trade ideas generated by the LLM ideas engine (long / short / hedge / watch / avoid) with thesis, catalyst, confidence, and instruments. Independent from the chat LLM.',
      parameters: {
        type: 'object',
        properties: {
          limit: { type: 'integer', default: 5 },
        },
        required: [],
      },
    },
  },
  {
    type: 'function',
    function: {
      name: 'get_chokepoint_status',
      description: 'Maritime chokepoint status: recent AIS activity near named chokepoints, capacity notes, and any ship-tracking flags. Valid names: hormuz, suez, malacca, bab-el-mandeb, taiwan, bosporus, panama, good-hope. Omit the name to get a list of all chokepoints.',
      parameters: {
        type: 'object',
        properties: {
          chokepoint: {
            type: 'string',
            description: 'Optional chokepoint slug. Omit to list all.',
          },
        },
        required: [],
      },
    },
  },
  {
    type: 'function',
    function: {
      name: 'get_region_snapshot',
      description: 'Geographic slice: returns recent events (ACLED conflicts, FIRMS thermal anomalies, GDELT news, ADS-B military flights, AIS ships) within a radius of a lat/lon. Useful for "what is happening in X" queries.',
      parameters: {
        type: 'object',
        properties: {
          lat: { type: 'number', description: 'Latitude (decimal degrees)' },
          lon: { type: 'number', description: 'Longitude (decimal degrees)' },
          radiusKm: { type: 'number', description: 'Radius in kilometers (default 500)', default: 500 },
        },
        required: ['lat', 'lon'],
      },
    },
  },
  {
    type: 'function',
    function: {
      name: 'get_market_snapshot',
      description: 'Current market state: equity indices, commodities (WTI, Brent, natgas, gold), FX, VIX, HY spreads, and the most recent candles. Use this before reasoning about market impact of an event.',
      parameters: { type: 'object', properties: {}, required: [] },
    },
  },
];

// ─── Tool executors ─────────────────────────────────────────────────────────

export function buildToolExecutors({ getCurrentData, getMemory }) {
  const get = () => {
    const d = getCurrentData();
    if (!d) throw new Error('No sweep data yet — initial sweep still in progress');
    return d;
  };

  return {
    get_briefing_summary: () => {
      const d = get();
      const vix = d.fred?.find(f => f.id === 'VIXCLS');
      const hy = d.fred?.find(f => f.id === 'BAMLH0A0HYM2');
      const delta = d.delta?.summary || null;
      return {
        timestamp: d.meta?.timestamp || new Date().toISOString(),
        sources: {
          ok: d.meta?.sourcesOk || 0,
          failed: d.meta?.sourcesFailed || 0,
          total: d.meta?.sourcesQueried || 0,
        },
        direction: delta?.direction || 'unknown',
        changes: {
          total: delta?.totalChanges || 0,
          critical: delta?.criticalChanges || 0,
        },
        headline_metrics: {
          vix: vix?.value ?? null,
          wti: d.energy?.wti ?? null,
          brent: d.energy?.brent ?? null,
          natgas: d.energy?.natgas ?? null,
          hy_spread: hy?.value ?? null,
        },
        osint_posts: d.tg?.posts || 0,
        urgent_signals: d.tg?.urgent?.length || 0,
      };
    },

    list_sources: () => {
      const d = get();
      const sources = [];
      for (const [key, value] of Object.entries(d)) {
        if (!value || typeof value !== 'object') continue;
        if (['meta', 'delta', 'ideas', 'ideasSource', 'news', 'newsFeed', 'tg', 'energy'].includes(key)) continue;
        if (Array.isArray(value)) {
          sources.push({ name: key, type: 'array', count: value.length });
        } else {
          sources.push({ name: key, type: 'object', keys: Object.keys(value).slice(0, 10) });
        }
      }
      // Always advertise the canonical source list so the LLM sees options even
      // when a source returned an empty payload this sweep.
      const canonical = ['gdelt', 'opensky', 'adsb', 'firms', 'ships', 'safecast', 'acled',
        'reliefweb', 'who', 'ofac', 'opensanctions', 'fred', 'treasury', 'bls', 'eia',
        'gscpi', 'usaspending', 'comtrade', 'noaa', 'epa', 'patents', 'bluesky', 'reddit',
        'telegram', 'kiwisdr', 'space', 'yfinance'];
      return {
        present: sources,
        canonical,
      };
    },

    query_source: ({ source, limit = 20 }) => {
      const d = get();
      const payload = d[source];
      if (payload === undefined) {
        return { error: `Source "${source}" not found in current sweep. Call list_sources for valid names.` };
      }
      if (Array.isArray(payload)) {
        return { source, count: payload.length, data: trimArray(payload, limit) };
      }
      if (payload && typeof payload === 'object') {
        // Trim array fields inside the object
        const out = {};
        for (const [k, v] of Object.entries(payload)) {
          out[k] = Array.isArray(v) ? trimArray(v, limit) : v;
        }
        return { source, data: out };
      }
      return { source, data: payload };
    },

    get_active_alerts: ({ limit = 10 } = {}) => {
      const d = get();
      const delta = d.delta;
      if (!delta) return { alerts: [], message: 'No delta data yet' };
      const all = [
        ...(delta.critical || []).map(a => ({ ...a, severity: 'critical' })),
        ...(delta.notable || []).map(a => ({ ...a, severity: 'notable' })),
      ];
      return {
        summary: delta.summary || null,
        alerts: all.slice(0, limit),
      };
    },

    get_trade_ideas: ({ limit = 5 } = {}) => {
      const d = get();
      return {
        source: d.ideasSource || 'unknown',
        ideas: (d.ideas || []).slice(0, limit),
      };
    },

    get_chokepoint_status: ({ chokepoint } = {}) => {
      if (!chokepoint) {
        return { chokepoints: CHOKEPOINTS };
      }
      const key = String(chokepoint).toLowerCase();
      const cp = CHOKEPOINTS[key];
      if (!cp) return { error: `Unknown chokepoint "${chokepoint}"`, valid: Object.keys(CHOKEPOINTS) };
      const d = get();
      const ships = d.ships || {};
      return {
        chokepoint: cp,
        ais_status: ships.status || 'unknown',
        message: ships.message || null,
        capabilities: ships.monitoringCapabilities || [],
        note: 'Real-time AIS vessel positions require the WebSocket listener. Current payload is a snapshot.',
      };
    },

    get_region_snapshot: ({ lat, lon, radiusKm = 500 } = {}) => {
      if (typeof lat !== 'number' || typeof lon !== 'number') {
        return { error: 'lat and lon are required numeric parameters' };
      }
      const d = get();
      const within = (pt) => {
        if (pt == null) return false;
        const la = pt.lat ?? pt.latitude ?? pt[0];
        const lo = pt.lon ?? pt.lng ?? pt.longitude ?? pt[1];
        if (typeof la !== 'number' || typeof lo !== 'number') return false;
        return haversine(lat, lon, la, lo) <= radiusKm;
      };

      const result = {
        center: { lat, lon, radiusKm },
        acled: trimArray((d.acled?.events || []).filter(within), 25),
        firms: trimArray((d.firms?.detections || d.firms?.events || []).filter(within), 25),
        gdelt: trimArray((d.gdelt?.events || []).filter(e =>
          typeof e.lat === 'number' && typeof e.lon === 'number' &&
          haversine(lat, lon, e.lat, e.lon) <= radiusKm
        ), 25),
        news: trimArray((d.newsFeed || []).filter(n =>
          typeof n.lat === 'number' && typeof n.lon === 'number' &&
          haversine(lat, lon, n.lat, n.lon) <= radiusKm
        ), 25),
      };
      return result;
    },

    get_market_snapshot: () => {
      const d = get();
      const indices = {};
      const commods = {};
      const fx = {};
      const yf = d.yfinance || {};
      for (const [k, v] of Object.entries(yf)) {
        if (!v || typeof v !== 'object') continue;
        if (/^(SPY|QQQ|DIA|IWM|VIX|\^GSPC|\^DJI|\^IXIC|\^VIX|\^RUT)$/i.test(k)) indices[k] = v;
        else if (/(BZ=F|CL=F|NG=F|GC=F|SI=F|HG=F)/i.test(k)) commods[k] = v;
        else if (/(EUR|USD|JPY|GBP|CNY|DXY)/i.test(k)) fx[k] = v;
      }
      const vix = d.fred?.find(f => f.id === 'VIXCLS');
      const hy = d.fred?.find(f => f.id === 'BAMLH0A0HYM2');
      return {
        indices,
        commodities: {
          wti: d.energy?.wti ?? null,
          brent: d.energy?.brent ?? null,
          natgas: d.energy?.natgas ?? null,
          ...commods,
        },
        fx,
        volatility: { vix: vix?.value ?? null },
        credit: { hy_spread: hy?.value ?? null },
        timestamp: d.meta?.timestamp || new Date().toISOString(),
      };
    },
  };
}

// ─── Tool-use loop ──────────────────────────────────────────────────────────

/**
 * Run an OpenAI-style tool-use loop against the provider.
 * Supports both modern tool_calls[] format and legacy function_call format.
 *
 * @param {object} provider  Any provider exposing chat({messages, tools, ...})
 * @param {Array}  messages  Initial messages (system + user + optional history)
 * @param {object} executors Map of tool-name → sync/async function
 * @param {object} opts      { maxSteps: 6, tools: TOOL_SCHEMAS, temperature, maxTokens, onStep }
 */
export async function runToolLoop(provider, messages, executors, opts = {}) {
  const maxSteps = opts.maxSteps ?? 6;
  const tools = opts.tools || TOOL_SCHEMAS;
  const history = [...messages];
  const trace = [];

  for (let step = 0; step < maxSteps; step++) {
    if (!provider.chat) {
      throw new Error(`Provider "${provider.name}" does not implement chat() — tool-use requires it.`);
    }
    const resp = await provider.chat(history, {
      tools,
      toolChoice: opts.toolChoice || 'auto',
      temperature: opts.temperature,
      maxTokens: opts.maxTokens,
    });

    const toolCalls = resp.toolCalls || [];
    if (!toolCalls.length) {
      trace.push({ step, type: 'final', content: resp.text });
      return { text: resp.text, history, trace, steps: step + 1 };
    }

    // Record the assistant turn that requested the tools
    history.push({
      role: 'assistant',
      content: resp.text || null,
      tool_calls: toolCalls,
    });

    // Execute every requested tool and append tool messages
    for (const call of toolCalls) {
      const name = call.function?.name;
      let args = {};
      try {
        args = call.function?.arguments ? JSON.parse(call.function.arguments) : {};
      } catch (e) {
        args = { _parse_error: e.message, _raw: call.function?.arguments };
      }

      let result;
      try {
        const exec = executors[name];
        if (!exec) {
          result = { error: `Unknown tool: ${name}` };
        } else {
          result = await exec(args);
        }
      } catch (e) {
        result = { error: e.message };
      }

      trace.push({ step, type: 'tool', name, args, result: typeof result === 'object' ? result : { result } });

      history.push({
        role: 'tool',
        tool_call_id: call.id,
        name,
        content: JSON.stringify(result).slice(0, 24000), // cap per-tool payload
      });

      if (opts.onStep) opts.onStep({ step, name, args, result });
    }
  }

  // Ran out of steps — force a final answer
  history.push({
    role: 'system',
    content: `Tool-use budget exhausted (${maxSteps} steps). Produce a final answer now with the information gathered.`,
  });
  const finalResp = await provider.chat(history, { temperature: opts.temperature, maxTokens: opts.maxTokens });
  trace.push({ step: maxSteps, type: 'forced_final', content: finalResp.text });
  return { text: finalResp.text, history, trace, steps: maxSteps + 1 };
}

export const CHAT_SYSTEM_PROMPT = `You are the S.O.N consigliere: a geopolitical + market intelligence analyst with direct tool access to a live OSINT sweep covering 27 sources (GDELT, FIRMS thermal, ADS-B, OpenSky, AIS maritime, ACLED conflict, FRED macro, Treasury, EIA energy, yfinance markets, Telegram/Bluesky/Reddit OSINT channels, CelesTrak satellites, and more).

Operating rules:
1. Always ground claims in tool-returned data. Call get_briefing_summary first on any open-ended question so you know the current posture.
2. For regional questions ("what's happening in Iran", "Hormuz status"), call get_region_snapshot or get_chokepoint_status.
3. For market questions, call get_market_snapshot before reasoning about direction or impact.
4. Chain tools when useful. Budget: up to 6 tool calls per turn.
5. Be direct. No corporate hedging, no "as an AI language model". Sean is the operator; give him signal, not padding.
6. When data is stale or a source is failing, say so explicitly rather than guessing.
7. Timestamps in UTC unless a region-specific timezone is clearly implied.
8. If asked about anything not covered by your tools (classified, subscription-only, etc.), say so — do not fabricate.

Format: prose, tight paragraphs, minimal bullets. Lead with the answer, then the evidence.`;
